# Generated by Django 4.0.2 on 2022-02-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_slog_category_slug_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
