# Generated by Django 4.0.2 on 2022-02-07 22:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_remove_category_slug_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picker',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
